---
# Wazuh post-install tasks

# REMOVED: Read lme-environment.env file
# REMOVED: Set environment variables

- name: Set playbook variables
  ansible.builtin.set_fact:
    wazuh_password: "{{ global_secrets.wazuh | default('') }}"
    wazuh_api_password: "{{ global_secrets.wazuh_api | default('') }}"

# Configure offline CVE database for vulnerability detection
- name: Configure Wazuh for offline CVE database
  ansible.builtin.replace:
    path: "/opt/lme/config/wazuh_cluster/wazuh_manager.conf"
    regexp: '(<vulnerability-detection>[\s\S]*?<feed-update-interval>60m</feed-update-interval>)([\s\S]*?</vulnerability-detection>)'
    replace: '\1\n     <offline-url>/opt/lme/cve/cves.zip</offline-url>\2'
    backup: yes
  become: yes
  when: offline_mode | default(false)

# Add volume mount for CVE database in offline mode
- name: Add CVE database volume mount to Wazuh container
  ansible.builtin.lineinfile:
    path: "/etc/containers/systemd/lme-wazuh-manager.container"
    line: "Volume=/opt/lme/cve:/opt/lme/cve:ro"
    insertafter: "^Volume=.*wazuh.*"
    backup: yes
  become: yes
  when: offline_mode | default(false)

# Fix Wazuh RBAC
- name: Fix Wazuh RBAC
  ansible.builtin.expect:
    command: "{{ clone_directory }}/scripts/wazuh_rbac.sh"
    responses:
      ".*'wazuh'.*":
        - "{{ wazuh_password }}"
      ".*'wazuh-wui'.*":
        - "{{ wazuh_api_password }}"
    timeout: 240
  become: yes
  no_log: "{{ not debug_mode }}"