services:
  lme:
    build: 
      context: .
      dockerfile: Dockerfile
      target: lme
      args:
        USER_ID: "${HOST_UID:-1001}"
        GROUP_ID: "${HOST_GID:-1001}"
    container_name: lme
    working_dir: /root
    volumes:
      - ../../LME:/root/LME
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    privileged: true
    stop_signal: SIGRTMIN+3
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    environment:
      - PODMAN_IGNORE_CGROUPSV1_WARNING=1
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
    command: ["/lib/systemd/systemd"]
    ports:
      - "5601:5601"
      - "443:443"
      - "8220:8220"
      - "9200:9200"

