---
# Quadlet setup tasks for podman role
# AUTOMATICALLY ADAPTS to SELinux vs non-SELinux environments

- name: Copy config files /opt/lme/config
  copy:
    src: "{{ clone_directory }}/config/"
    dest: /opt/lme/config/
    owner: "{{ install_user }}"
    group: "{{ install_user }}"
    mode: '0644'
  become: yes

- name: Create /etc/containers/systemd with environment-appropriate permissions
  file:
    path: /etc/containers/systemd
    state: directory
    owner: "root"
    group: "root"
    mode: '{{ "0755" if (ansible_os_family == "RedHat" and ansible_selinux.status == "enabled") else "0755" }}'
  become: yes

- name: Copy quadlet files to /etc/containers/systemd 
  copy:
    src: "{{ clone_directory }}/quadlet/"
    dest: /etc/containers/systemd/
    owner: "root"
    group: "root"
    mode: '0644'
  become: yes

- name: copy lme.service to /etc/systemd/system
  copy:
    src: "{{ clone_directory }}/quadlet/lme.service"
    dest: "/etc/systemd/system/lme.service"
    owner: "root"
    group: "root"
    mode: '0644'
  become: yes

# =====================================================
# ENVIRONMENT-AWARE QUADLET SETUP
# =====================================================

- name: Display environment detection
  debug:
    msg: |
      🔍 ENVIRONMENT DETECTION:
      OS Family: {{ ansible_os_family }}
      SELinux Status: {{ ansible_selinux.status | default('not present') }}
      Quadlet Generator Workaround: {{ 'ENABLED' if (ansible_os_family == 'RedHat') else 'SKIPPED (not needed on non-RHEL)' }}

# =====================================================
# PODMAN QUADLET GENERATOR WORKAROUND (RHEL/CentOS)
# =====================================================
# systemd doesn't automatically run quadlet generators on some RHEL systems
# This manually generates and installs the container services
# ONLY RUNS on RedHat family systems where the issue exists

- name: Generate Podman quadlet services (systemd generator workaround for RHEL/CentOS)
  block:
    - name: Check if quadlet configuration files exist
      stat:
        path: /etc/containers/systemd
      register: quadlet_dir

    - name: Run Podman quadlet generator to create service files
      command: >
        /usr/lib/systemd/system-generators/podman-system-generator
        /tmp/quadlet-generator-output 
        /tmp/quadlet-generator-output.early 
        /tmp/quadlet-generator-output.late
      when: quadlet_dir.stat.exists and quadlet_dir.stat.isdir
      changed_when: true

    - name: Find generated service files
      find:
        paths: 
          - /tmp/quadlet-generator-output
          - /tmp/quadlet-generator-output.early  
          - /tmp/quadlet-generator-output.late
        patterns: "*.service"
        file_type: file
      register: generated_services
      when: quadlet_dir.stat.exists

    - name: Copy generated services to systemd system directory
      copy:
        src: "{{ item.path }}"
        dest: "/etc/systemd/system/{{ item.path | basename }}"
        remote_src: true
        mode: '0644'
        owner: root
        group: root
      loop: "{{ generated_services.files }}"
      when: 
        - quadlet_dir.stat.exists
        - generated_services.files is defined
        - generated_services.files | length > 0
      notify: reload systemd daemon

    - name: Clean up temporary generator directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/quadlet-generator-output
        - /tmp/quadlet-generator-output.early
        - /tmp/quadlet-generator-output.late
      when: quadlet_dir.stat.exists

    - name: Debug generated services
      debug:
        msg: "Generated {{ generated_services.files | length | default(0) }} quadlet service files for RHEL/CentOS system"
      when: generated_services.files is defined

  when: 
    - ansible_os_family == "RedHat"
    - enable_quadlet_generator_workaround | default(true)
  become: yes

# =====================================================
# STANDARD QUADLET SETUP (Ubuntu/Debian)
# =====================================================
# On Ubuntu/Debian, systemd typically handles quadlets properly

- name: Configure quadlets for Ubuntu/Debian systems
  block:
    - name: Display Ubuntu/Debian quadlet status
      debug:
        msg: |
          ℹ️  UBUNTU/DEBIAN ENVIRONMENT
          🔧 Using standard systemd quadlet processing
          ✅ No generator workaround needed

    - name: Verify quadlet directory exists
      stat:
        path: /etc/containers/systemd
      register: quadlet_dir_ubuntu

    - name: Note quadlet configuration
      debug:
        msg: "Quadlet files configured in /etc/containers/systemd ({{ 'directory exists' if quadlet_dir_ubuntu.stat.exists else 'directory missing' }})"

  when: 
    - ansible_os_family != "RedHat"

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  become: yes

# =====================================================
# ENABLE LME SERVICES (All Environments)
# =====================================================

- name: Enable generated LME container services
  systemd:
    name: "{{ item }}"
    enabled: yes
    daemon_reload: false  # Already done above
  loop:
    - lme-elasticsearch.service
    - lme-kibana.service
    - lme-wazuh-manager.service
    - lme-fleet-server.service
    - lme-elastalert.service
    - lme-setup-certs.service
    - lme-setup-accts.service
    - lme-network.service
    - lme-esdata01-volume.service
    - lme-kibanadata-volume.service
    - lme-backups-volume.service
  failed_when: false  # Some services might not exist depending on configuration
  when: quadlet_services_auto_enable | default(true)
  become: yes

- name: Start LME service
  systemd:
    name: lme.service
    state: started
    enabled: yes
  become: yes

- name: Display final quadlet setup status
  debug:
    msg: |
      ✅ Podman quadlet setup completed for {{ ansible_distribution }} {{ ansible_distribution_version }}
      
      📁 CONFIGURED:
      - /etc/containers/systemd/ directory created with correct permissions
      - Quadlet configuration files copied from {{ clone_directory }}/quadlet/
      - Main lme.service installed in /etc/systemd/system/
      
      🔧 ENVIRONMENT-SPECIFIC SETUP:
      {% if ansible_os_family == "RedHat" %}
      - RHEL/CentOS: Manual quadlet generator workaround applied
      - Generated container services copied to /etc/systemd/system/
      - SELinux integration {{ 'enabled' if ansible_selinux.status == 'enabled' else 'skipped (SELinux disabled)' }}
      {% else %}
      - Ubuntu/Debian: Standard systemd quadlet processing used
      - No generator workaround needed
      {% endif %}
      
      📋 SERVICE MANAGEMENT:
      - Individual LME services {{ 'enabled automatically' if (quadlet_services_auto_enable | default(true)) else 'require manual enablement' }}
      - Main lme.service started and enabled
      
      🎯 RESULT: LME container services should be available via systemctl on all platforms!