---
# This role only runs when nix is actually needed (no suitable podman found)
# The podman version checking is now done in pre_tasks in site.yml

# Include OS-specific variables
- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
    - "default.yml"

# Include OS-specific tasks
- name: Include OS-specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
    - "common.yml"

# These tasks are common to all distributions when nix is installed
- name: Update PATH for Ansible execution
  set_fact:
    ansible_env: "{{ ansible_env | combine({'PATH': ansible_env.PATH ~ ':/nix/var/nix/profiles/default/bin'}) }}"

- name: Update PATH in user's profile
  lineinfile:
    path: "~/.profile"
    line: 'export PATH=$PATH:/nix/var/nix/profiles/default/bin'
    create: yes

- name: Update PATH in root's profile 
  lineinfile:
    path: "/root/.profile"
    line: 'export PATH=$PATH:/nix/var/nix/profiles/default/bin'
    create: yes
  become: yes

- name: Update PATH in user's bashrc
  lineinfile:
    path: "~/.bashrc"
    line: 'export PATH=$PATH:/nix/var/nix/profiles/default/bin'
    create: yes

- name: Update PATH in root's bashrc
  lineinfile:
    path: "/root/.bashrc"
    line: 'export PATH=$PATH:/nix/var/nix/profiles/default/bin'
    create: yes
  become: yes

# Configure SELinux for Nix-installed container tools (before creating symlinks)
- name: Check if SELinux is enabled for Nix integration
  command: getenforce
  register: nix_selinux_check
  changed_when: false
  failed_when: false

- name: Configure SELinux policies for Nix container runtime tools
  include_tasks: selinux_integration.yml
  when: 
    - ansible_os_family == "RedHat"
    - nix_selinux_check is defined 
    - nix_selinux_check.rc == 0
    - nix_selinux_check.stdout in ['Enforcing', 'Permissive']

- name: Create podman symlink for sudo access
  file:
    src: "/nix/var/nix/profiles/default/bin/podman"
    dest: "/usr/local/bin/podman"
    state: link
    force: yes
  become: yes
  ignore_errors: yes

- name: Source updated PATH
  shell: source ~/.profile
  args:
    executable: /bin/bash 