---
# Include OS-specific variables
- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
    - "default.yml"

# Include OS-specific tasks
- name: Include OS-specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
    - "common.yml"

# These tasks are common to all distributions
- name: Update PATH for Ansible execution
  set_fact:
    ansible_env: "{{ ansible_env | combine({'PATH': ansible_env.PATH ~ ':/nix/var/nix/profiles/default/bin'}) }}"

- name: Update PATH in user's profile
  lineinfile:
    path: "~/.profile"
    line: 'export PATH=$PATH:/nix/var/nix/profiles/default/bin'
    create: yes

- name: Update PATH in root's profile 
  lineinfile:
    path: "/root/.profile"
    line: 'export PATH=$PATH:/nix/var/nix/profiles/default/bin'
    create: yes
  become: yes

- name: Update PATH in user's bashrc
  lineinfile:
    path: "~/.bashrc"
    line: 'export PATH=$PATH:/nix/var/nix/profiles/default/bin'
    create: yes

- name: Update PATH in root's bashrc
  lineinfile:
    path: "/root/.bashrc"
    line: 'export PATH=$PATH:/nix/var/nix/profiles/default/bin'
    create: yes
  become: yes

- name: Create podman symlink for sudo access
  file:
    src: "/nix/var/nix/profiles/default/bin/podman"
    dest: "/usr/local/bin/podman"
    state: link
    force: yes
  become: yes
  ignore_errors: yes

- name: Create podman symlink in /usr/bin for systemd generators
  file:
    src: "{{ nix_profile_symlink_path }}/bin/podman"
    dest: /usr/bin/podman
    state: link
    force: yes
  become: yes

- name: Ensure correct podman systemd generator is linked in the nix profile
  file:
    src: "{{ nix_profile_symlink_path }}/libexec/podman/quadlet"
    dest: "{{ nix_profile_symlink_path }}/lib/systemd/system-generators/podman-system-generator"
    state: link
    force: yes
  become: yes

- name: Restore contexts on podman symlinks (best-effort)
  command: restorecon -v /usr/local/bin/podman /usr/bin/podman
  changed_when: false
  failed_when: false
  become: yes

- name: Source updated PATH
  shell: source ~/.profile
  args:
    executable: /bin/bash 

# ---------------------------------------------------------------------------
# Nix SELinux policy: deploy, compile, load, and label after Nix is installed
# ---------------------------------------------------------------------------
- name: Deploy Nix SELinux policy files
  copy:
    src: "{{ clone_directory }}/ansible/roles/base/files/selinux/nix_policy.te"
    dest: /etc/selinux/lme/nix_policy.te
    owner: root
    group: root
    mode: '0644'
  become: yes
  when:
    - selinux_available | default(false)

- name: Deploy Nix SELinux file contexts
  copy:
    src: "{{ clone_directory }}/ansible/roles/base/files/selinux/nix_policy.fc"
    dest: /etc/selinux/lme/nix_policy.fc
    owner: root
    group: root
    mode: '0644'
  become: yes
  when:
    - selinux_available | default(false)

- name: Compile Nix SELinux module
  shell: |
    set -e
    cd /etc/selinux/lme
    checkmodule -M -m -o nix_policy.mod nix_policy.te
    semodule_package -o nix_policy.pp -m nix_policy.mod -f nix_policy.fc
  args:
    executable: /bin/bash
  become: yes
  when:
    - selinux_available | default(false)
    - (getenforce_out.stdout | default('') | trim) != 'Disabled'

- name: Load Nix SELinux module
  command: semodule -i /etc/selinux/lme/nix_policy.pp
  become: yes
  when:
    - selinux_available | default(false)
    - (getenforce_out.stdout | default('') | trim) != 'Disabled'

- name: Ensure Nix SELinux module enabled
  command: semodule -e nix_policy
  become: yes
  when:
    - selinux_available | default(false)
    - (getenforce_out.stdout | default('') | trim) != 'Disabled'

- name: Check if nix profile exists
  stat:
    path: "{{ nix_profile_symlink_path }}"
  register: nix_profile_exists

- name: Restore context for nix profile (post-install)
  command: restorecon -Rv "{{ nix_profile_symlink_path }}"
  become: yes
  changed_when: false
  when:
    - selinux_available | default(false)
    - (getenforce_out.stdout | default('') | trim) != 'Disabled'
    - nix_profile_exists.stat.exists

- name: Restore context for Nix daemon socket directory
  command: restorecon -Rv /nix/var/nix/daemon-socket
  become: yes
  changed_when: false
  when:
    - selinux_available | default(false)
    - (getenforce_out.stdout | default('') | trim) != 'Disabled'