---
# Red Hat-specific Nix setup

- name: Detect if SELinux tooling is available
  command: which getenforce
  register: selinux_tooling
  changed_when: false
  failed_when: false
  become: yes

- name: Set SELinux availability fact
  set_fact:
    selinux_available: "{{ selinux_tooling.rc == 0 }}"

- name: Get current SELinux mode
  command: getenforce
  register: getenforce_out
  changed_when: false
  failed_when: false
  become: yes
  when: selinux_available | default(false)

- name: Remember if SELinux was enforcing
  set_fact:
    selinux_was_enforcing: "{{ selinux_available | default(false) and (getenforce_out.stdout | default('') | trim) == 'Enforcing' }}"

- name: Set SELinux to permissive for Nix install
  command: setenforce 0
  when: selinux_was_enforcing
  become: yes

- name: Check if Nix is already installed
  stat:
    path: /nix/var/nix/profiles/default/bin/nix
  register: nix_installed

- name: Create nix installation directory  
  file:
    path: /opt/nix-install
    state: directory
    mode: '0755'
  become: yes
  when: not nix_installed.stat.exists

- name: Create temporary directory for Nix install
  file:
    path: /opt/nix-install/tmp
    state: directory
    mode: '0755'
  become: yes
  when: not nix_installed.stat.exists

- name: Download Nix installer
  get_url:
    url: https://nixos.org/nix/install
    dest: /opt/nix-install/install-nix.sh
    mode: '0755'
  become: yes
  when: not nix_installed.stat.exists

- name: Install Nix package manager
  shell: sh /opt/nix-install/install-nix.sh --daemon --yes
  become: yes
  environment:
    TMPDIR: /opt/nix-install/tmp
  when: not nix_installed.stat.exists
  register: nix_install_result

- name: Debug Nix installation result
  debug:
    var: nix_install_result
  when: debug_mode | default(false) and not nix_installed.stat.exists

- name: Ensure nix-daemon service is started
  systemd:
    name: nix-daemon
    state: started
    enabled: yes
  become: yes
  when: not nix_installed.stat.exists

- name: Add Nix channel
  command: nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
  become: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:/nix/var/nix/profiles/default/bin"

- name: Update Nix channel
  command: nix-channel --update
  become: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:/nix/var/nix/profiles/default/bin"

- name: Check if nix-users group exists
  group:
    name: nix-users
    state: present
  become: yes

- name: Add user to nix-users group
  user:
    name: "{{ install_user }}"
    groups: nix-users
    append: yes
  become: yes

- name: Install required packages
  command: nix-env -iA nixpkgs.podman nixpkgs.docker-compose
  become: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:/nix/var/nix/profiles/default/bin"

- name: Ensure SELinux policy tools are present
  package:
    name:
      - policycoreutils
      - policycoreutils-python-utils
      - checkpolicy
      - libsemanage-devel
    state: present
  become: yes

- name: Deploy container-wide SELinux TE (container_policy)
  copy:
    src: selinux/container_policy.te
    dest: /etc/selinux/lme/container_policy.te
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Compile SELinux module (container_policy)
  shell: |
    set -e
    mkdir -p /etc/selinux/lme
    checkmodule -M -m -o /etc/selinux/lme/container_policy.mod /etc/selinux/lme/container_policy.te
    semodule_package -o /etc/selinux/lme/container_policy.pp -m /etc/selinux/lme/container_policy.mod
  args:
    executable: /bin/bash
  become: yes

- name: Load SELinux module (container_policy)
  command: semodule -i /etc/selinux/lme/container_policy.pp
  become: yes
  register: semodule_load
  changed_when: semodule_load.rc == 0
  failed_when: false

- name: Verify SELinux module loaded
  command: semodule -l
  register: semodule_list
  changed_when: false
  become: yes

- name: Assert container_policy module present
  assert:
    that:
      - semodule_list.stdout is search("^container_policy(\\s|$)")
    fail_msg: "container_policy module not loaded"

- name: Restore SELinux enforcing mode
  command: setenforce 1
  when: selinux_was_enforcing
  become: yes

- name: Persist SELinux enforcement across reboots (optional)
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=enforcing'
    create: no
  when: selinux_was_enforcing
  become: yes
